//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AeroProPlanProductionApp.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBPlanProductEntities : DbContext
    {
        public static DBPlanProductEntities _context;

        public DBPlanProductEntities()
            : base("name=DBPlanProductEntities")
        {
        }
        public static DBPlanProductEntities GetContext()
        {
            if (_context == null)
                _context = new DBPlanProductEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Balloon> Balloons { get; set; }
        public virtual DbSet<HistoryLogin> HistoryLogins { get; set; }
        public virtual DbSet<PlanProduction> PlanProductions { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductType> ProductTypes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
